### ISSUE TITLE
common.lib import forces CWD to be /

### ISSUE THREAD

**Issue by MerlinDMC** [joyent/sdc-vmtools-lx-brand#10]
`. ./lib/smartdc/common.lib` will only succeed if the calling process is run from `/`

should either be `. /lib/smartdc/common.lib` or determine the lib folder path prior to the import like

```
. $(cd $(dirname $0) && pwd)/common.lib
```

or 

```
. $(realpath $(dirname $0))/common.lib
```

`realpath` seems to be available in the busybox sh as well.

**Comment by chorrell** [comment]
I think my preference would be to just use the full path:

```
. /lib/smartdc/common.lib
```
