### ISSUE TITLE
user-script output in triton.log would be a nice plus

### ISSUE THREAD

**Issue by sjorge** [joyent/sdc-vmtools-lx-brand#22]
On native zones `tail -f `svcs -L mdata:execute`` get you the output of the user script.
There is no way (that I know of) to get the output in LX zones. It would be nice that it ends up in triton.log

Re-opened here as per @chorrell

**Comment by chorrell** [comment]
Redirecting the output to triton.log might be tricky, but I think having a separate user-script.log would be easy enough

**Comment by sjorge** [comment]
That would might even be better.

**Comment by chorrell** [comment]
I made the following changes to `mdata-execute` to enable logging:

```
USER_SCRIPT_LOG=/var/log/mdata-user-script.log
  if [[ ! -e $USER_SCRIPT_LOG ]]; then
    touch $USER_SCRIPT_LOG
  fi
  /var/svc/mdata-user-script >> $USER_SCRIPT_LOG 2>&1
```
